name: Schedule Bot Runtime

on:
  schedule:
    - cron: '0 2 * * *'    # 05:00 по Киеву — запуск
    - cron: '0 20 * * *'   # 23:00 по Киеву — остановка

jobs:
  start-bot:
    if: github.event.schedule == '0 2 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Start Railway Service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          PROJECT_NAME: "pretty-comfort"
          SERVICE_NAME: "telegram-content-bot"
        run: |
          get_project_id() {
            curl -s -H "Authorization: $RAILWAY_TOKEN" https://backboard.railway.app/graphql \
              -d '{"query":"{ projects { edges { node { id name }}}}"}' \
              | jq -r --arg name "$PROJECT_NAME" '.data.projects.edges[].node | select(.name==$name) | .id'
          }

          get_service_id() {
            curl -s -H "Authorization: $RAILWAY_TOKEN" https://backboard.railway.app/graphql \
              -d "{\"query\":\"{ project(id: \\\"$1\\\") { services { edges { node { id name }}}}}\"}" \
              | jq -r --arg name "$SERVICE_NAME" '.data.project.services.edges[].node | select(.name==$name) | .id'
          }

          PROJECT_ID=$(get_project_id)
          SERVICE_ID=$(get_service_id "$PROJECT_ID")

          curl -s -X POST https://backboard.railway.app/graphql \
            -H "Authorization: $RAILWAY_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"query\":\"mutation { serviceStart(id: \\\"$SERVICE_ID\\\") { id }}\"}"

  stop-bot:
    if: github.event.schedule == '0 20 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Stop Railway Service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          PROJECT_NAME: "pretty-comfort"
          SERVICE_NAME: "telegram-content-bot"
        run: |
          get_project_id() {
            curl -s -H "Authorization: $RAILWAY_TOKEN" https://backboard.railway.app/graphql \
              -d '{"query":"{ projects { edges { node { id name }}}}"}' \
              | jq -r --arg name "$PROJECT_NAME" '.data.projects.edges[].node | select(.name==$name) | .id'
          }

          get_service_id() {
            curl -s -H "Authorization: $RAILWAY_TOKEN" https://backboard.railway.app/graphql \
              -d "{\"query\":\"{ project(id: \\\"$1\\\") { services { edges { node { id name }}}}}\"}" \
              | jq -r --arg name "$SERVICE_NAME" '.data.project.services.edges[].node | select(.name==$name) | .id'
          }

          PROJECT_ID=$(get_project_id)
          SERVICE_ID=$(get_service_id "$PROJECT_ID")

          curl -s -X POST https://backboard.railway.app/graphql \
            -H "Authorization: $RAILWAY_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"query\":\"mutation { serviceStop(id: \\\"$SERVICE_ID\\\") { id }}\"}"

